# linkerd config for linker-to-linker mode
# routes from port 4140 on source node to 4141 on destination node

admin:
  ip: 0.0.0.0
  port: 9990

telemetry:
- kind: io.l5d.prometheus

usage:
  orgId: linkerd-examples-dcos-linker-linker

namers:
- kind: io.l5d.marathon
  host: marathon.mesos
  port: 8080

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  dtab: >- # route based on marathon name
    /marathonId => /#/io.l5d.marathon;
    /svc        => /$/io.buoyant.http.domainToPathPfx/marathonId;
  label: outgoing
  interpreter:
    kind: default
    transformers:
    # tranform all outgoing requests to deliver to incoming linkerd port 4141
    - kind: io.l5d.port
      port: 4141
- protocol: http
  servers:
  - port: 4141
    ip: 0.0.0.0
  dtab: >- # route based on marathon name
    /marathonId => /#/io.l5d.marathon;
    /svc        => /$/io.buoyant.http.domainToPathPfx/marathonId;
  label: incoming
  interpreter:
    kind: default
    transformers:
    # filter instances to only include those on this host
    - kind: io.l5d.localhost
