---
kind: ReplicationController
apiVersion: v1
metadata:
  namespace: default
  name: gen

spec:
  replicas: 1
  selector:
    app: gen
  template:
    metadata:
      labels:
        app: gen

    spec:
      dnsPolicy: ClusterFirst

      containers:
        - name: svc
          image: gobsvc/gob:0.8.6
          command:
            - gen
            - --srv=:8080
          ports:
            - name: grpc
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: gen
spec:
  selector:
    app: gen

  ports:
    - name: grpc
      port: 8080
