---
kind: ReplicationController
apiVersion: v1
metadata:
  namespace: default
  name: web

spec:
  replicas: 1
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web

    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: svc
          image: gobsvc/gob:0.8.6
          command:
            - web
            - --srv=:8080
            - --gen-addr=gen:8080
            - --word-addr=word:8080
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: web
spec:
  selector:
    app: web

  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
