---
kind: ReplicationController
apiVersion: v1
metadata:
  namespace: default
  name: word

spec:
  replicas: 1
  selector:
    app: word
  template:
    metadata:
      labels:
        app: word

    spec:
      dnsPolicy: ClusterFirst

      containers:
        - name: svc
          image: gobsvc/gob:0.8.6
          command:
            - word
            - --srv=:8080
          ports:
            - name: grpc
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: word
spec:
  selector:
    app: word

  ports:
    - name: grpc
      port: 8080
