# linkerd config for basic http proxy with namerd
# listens on port 4140, routes via http_proxy or host header
# all service discovery managed via namerd

admin:
  ip: 0.0.0.0
  port: 9990

telemetry:
- kind: io.l5d.prometheus

usage:
  orgId: linkerd-examples-dcos-linkerd-namerd

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  label: linkerd_proxy
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.marathon.mesos/4100
