# namerd config for use with linkerd
# http interface (for dtab api) on port 4180
# thrift interface (for linkerd) on port 4100

admin:
  ip: 0.0.0.0
  port: 9991

storage:
  kind: io.l5d.zk
  zkAddrs:
  - host: leader.mesos
    port: 2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000

namers:
- kind:         io.l5d.marathon
  host:         marathon.mesos
  port:         8080

interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip:   0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip:   0.0.0.0
  port: 4180
